[project]
name = "async-python-malware"
description = "Example malware written in Python to demo asyncio"
version = "1.0"

[project.urls]
Repository = "https://github.com/SocialExploits/async-python-malware.git"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/apm"]
